language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: bitshares/bitshares-ui
        - WALLET_REPO: bitshares/wallet.bitshares.org
        - STAGING_REPO: bitshares/bitshares-ui-staging
        - DEVELOP_REPO: bitshares/develop.bitshares.org
        - CXX=g++-4.8
        - secure:
              up459CkvN8cdhCHu4E2jAse5CM3JUJlVMbBu2x1HctFjanu4rv2JknIn5U4Rc6rX89GgLLJeUN05UsZEz+M+s5P7b8wlwkTKu1cdNFmcS1oDAJh3Gk22F3zGiv/HIQazjGCajMxX0kIsjNsHngAd/wJCvGrnLBU5vetu6zqCK/jR/YMGRl9bNTygH07eC4r5I7EKFRJLA8pM3GfBlG04aPS4feIrCiT+TAVENx3hLC2eKs451e3ktMYM5nh89E5HKjg2rfmwmIJRzuC/Rv5Dpk/3A77mOUe3iwZZWrmwUinlEfLBPn6zUD/XX83DI+7nINyUY13vDGZiMkwygvM6QZrReQZfZSVOaAfIZ7WoWIQd5SYFDj0fTGbdTxgwISr13LSHFQN+YsWkdbvnuKKXpaTwW+rRXU4pWXjaOQtNyr2nvp1AiW6TYzmq5ECbQ0IE2versZczasOLSk2E1h9vHw0SXrfqDR/X7WMIdKOuv1Umre30gcRZi5/0ZdcvfeY8jtdTwfsYoywtAQ3vfMelfDafIAtYPjFEhaeBZDDFGfMX5XAI0Rx34jQX7W1+76gR17l2V9kOwzKp/p5LNQh8kGzxyMY8Hl2xapwt/RG3tTnPXZeazFenYvybVCXPb46+Vqa/pxQyxB0HFu+izPTCiFfvd5rELyFkQT3kSNKFuio=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
after_success: "./deploy.sh"
deploy:
    - provider: releases
      tag_name: "$TRAVIS_TAG"
      name: "$TRAVIS_TAG"
      body:
          Automated release from Travis CI with added files from AppVeyor build
      api_key: "$GITHUB_TOKEN"
      file_glob: true
      file:
          - build/binaries/BitShares*
          - build/release-checksums-*
      skip_cleanup: true
      draft: true
      on:
          repo: bitshares/bitshares-ui
          tags: true
    - provider: snap
      snap: bitshares2-light
      channel: candidate
      skip_cleanup: true
      on:
          tags: true
before_install:
    - openssl aes-256-cbc -K $encrypted_844f3e8bd137_key -iv $encrypted_844f3e8bd137_iv
      -in set_snap_token.sh.enc -out set_snap_token.sh -d
    - chmod +x set_snap_token.sh
    - source ./set_snap_token.sh
